### ISSUE TITLE
Declaring a `List<>` of a collection item type causes unexpected results.

### ISSUE THREAD

**Issue by RoyTheunissen** [brunomikoski/ScriptableObjectCollection#110]
Declaring a list of a collection item type like this `[SerializeField] private List<AudioClipEventId> testList;` causes the list dropdown to act weirdly. It seems to incorrectly assume that the collection type is the encapsulating `List`.

Version is Unity `2021.3.2f1` and it uses the latest version of the ScriptableObjectCollection.

![image](https://user-images.githubusercontent.com/3997055/207107179-4d098a92-2722-4489-829a-ed114f5449b3.png)

**Comment by brunomikoski** [comment]
Fixed on https://github.com/brunomikoski/ScriptableObjectCollection/releases/tag/v1.9.6
