### ISSUE TITLE
ArgumentNullException when leaving Play Mode

### ISSUE THREAD

**Issue by LTorquato** [brunomikoski/ScriptableObjectCollection#116]
Unity Version: 2021.3.11f1
SOC Version: 1.9.6
Addressables Version: 1.19.19

Steps to reproduce:
1. Create a collection
2. Mark Automatically Loaded as false
3. Mark the Collection as Addressable Asset
4. Enter Play Mode
5. Load collection via Addressable
6. Exit Play Mode

`ArgumentNullException: Value cannot be null.
Parameter name: collection
System.Collections.Generic.List``1[T]..ctor (System.Collections.Generic.IEnumerable``1[T] collection) (at <612a2c65aaf843d698f8d38b2ad7654a>:0)
BrunoMikoski.ScriptableObjectCollections.ScriptableObjectCollection.PrepareForEditorMode () (at Library/PackageCache/com.brunomikoski.scriptableobjectcollection@1.9.6/Scripts/Runtime/Core/ScriptableObjectCollection.cs:392)
BrunoMikoski.ScriptableObjectCollections.CollectionsRegistry.PrepareForEditorMode () (at Library/PackageCache/com.brunomikoski.scriptableobjectcollection@1.9.6/Scripts/Runtime/Core/CollectionsRegistry.cs:306)
BrunoMikoski.ScriptableObjectCollections.EditorBehaviour.OnPlayModeStateChanged (UnityEditor.PlayModeStateChange playModeStateChange) (at Library/PackageCache/com.brunomikoski.scriptableobjectcollection@1.9.6/Scripts/Editor/Core/EditorBehaviour.cs:25)
UnityEditor.EditorApplication.Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange state) (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:438)
`
[SOCAddressablesTestProject.zip](https://github.com/brunomikoski/ScriptableObjectCollection/files/10294523/SOCAddressablesTestProject.zip)

**Comment by brunomikoski** [comment]
It should be fixed on 2.0.1
