### ISSUE TITLE
Adding via GIT Registry Package doesn't compile

### ISSUE THREAD

**Issue by mgmhunt** [brunomikoski/ScriptableObjectCollection#126]
Library/PackageCache/com.brunomikoski.scriptableobjectcollection@2.0.8/Scripts/Editor/CustomEditors/CollectionCustomEditor.cs(257,29): error CS0122: 'EditorCache' is inaccessible due to its protection level

Moving the package to the root 'Packages' folder allows compilation.

**Comment by brunomikoski** [comment]
That's weird. What version of unity you are using? 
Did you tried with[ [2.0.9]](https://github.com/brunomikoski/ScriptableObjectCollection/releases/tag/v2.0.9) ?

Looks like 2.0.8 had one issue with EditorCache but should be fixed on 2.0.9, just upgrade to it.

**Comment by mgmhunt** [comment]
yep upgrade fixed it
