### ISSUE TITLE
CollectionItem with Generic Inheritance (Unity Atoms)

### ISSUE THREAD

**Issue by mgmhunt** [brunomikoski/ScriptableObjectCollection#145]
Hi thanks for this library - trying to use it organise Unity Atoms - starting with Events but probably move on to Variables, Actions, Conditions etc.

I have classes derived from your library with Generics

```
public class AtomEventCollection<T> : ScriptableObjectCollection<AtomEventItem<T>>    
{    }
```
```
public abstract class AtomEventItem<T> : ScriptableObjectCollectionItem
    {
        [SerializeField]
        private AtomEvent<T> _event;
        public AtomEvent<T> Event
        {
            get { return _event; }
            set { _event = value; }
        }

.... this also automatically generates the AtomEvent<T> on creation and nests it under the CollectionItem
```
```
public class AtomEventIndirectReference<T> : CollectionItemIndirectReference<AtomEventItem<T>>    {
        public AtomEventIndirectReference() {}
        public AtomEventIndirectReference(AtomEventItem<T> collectionItemScriptableObject) : base(collectionItemScriptableObject) {}
    }
```
which then get made concrete like

`public partial class WorldGameEvent : AtomEventItem<World>    {    }`

`public class WorldGameEventCollection : AtomEventCollection<WorldGameEvent>    {    }`

As far as I can tell at this stage this is working.

**In order to get this working I've had to make the following edit on line 226 of ScriptableObjectCollection.cs**
` // DOESN'T WORK -> if (baseType.IsGenericType && baseType.GetGenericTypeDefinition() == typeof(ScriptableObjectCollection<>))

 if (baseType.IsGenericType) // edit mgmhunt`

as it's presuming the Generics are only the ScriptableObjectCollection<>.   I couldn't get IsSubClass of (probably to do with Generics again - **maybe you've got a cleaner way of fixing this?**)

My question is do you foresee issues down the road with this as I'm hoping this library will be broadly useful and not sure what this assumption my cause with other classes?

----- Working so far ----

```
WorldGameEvent testWorldEvent;
testWorldEvent.Event.Observe().TakeUntilDisable(this).Subscribe(_ => { LoadWorld(defaultWorld); }).AddTo(_subscriptions);
testWorldEvent.Event.Raise();
```

![Screen Shot 2024-05-18 at 09 43 49](https://github.com/brunomikoski/ScriptableObjectCollection/assets/273002/96d1d044-227b-41e8-bc0d-6bed51bec122)
![Screen Shot 2024-05-18 at 09 46 58](https://github.com/brunomikoski/ScriptableObjectCollection/assets/273002/01c8f52c-ed56-47d0-af78-0ab53e9ee41a)

**Comment by brunomikoski** [comment]
Yeah I think this should be fine, I will update to match your changes and follow close to the next release to see if cause any issues

**Comment by mgmhunt** [comment]
Cool yea haven't come across anything so far but it'll be a ways down the track before the number and type of Collections builds up so needed to test the waters a bit.
