### ISSUE TITLE
Namevalidation on items in the the collection could be improved

### ISSUE THREAD

**Issue by sezdev** [brunomikoski/ScriptableObjectCollection#48]
for example, any item starting with a number or symbol is invalid. Any keyword like "static" or "private" is invalid.

All these cases messes up the code generation.

**Comment by brunomikoski** [comment]
Actually, for numbers, I have a parser to text, but I could not reproduce the other ones, you mean when creating a new collection by the Creator Wizzard? Or adding a new collectable item o the collection?

**Comment by sezdev** [comment]
Adding a new collectable item to the collection, naming it "static" then pressing generate.

**Comment by brunomikoski** [comment]
Added CSharp keyword validation
