### ISSUE TITLE
Support multiple collections of the same type, and collections for the same collectable type

### ISSUE THREAD

**Issue by gsaurus** [brunomikoski/ScriptableObjectCollection#62]
There's a TryGetCollectionFromCollectableType. Would be nice to have a plural version, returning all collections for a collectable type.
Additionally, it would be nice for the drawer of a collectable type to display a collections dropdown when multiple collections exist for  that collectable type. This way user can select the collection, and an item from it.

**Comment by brunomikoski** [comment]
I think this one will be really tricky since this would require a lot of refactoring on how the property drawers works, I still believe this would be better fixed with the #51
