### ISSUE TITLE
Warning still visible after applying fix

### ISSUE THREAD

**Issue by Thundernerd** [brunomikoski/ScriptableObjectCollection#76]
When this warning appears and you apply the fix, the warning still shows.
Would be great if the warning would disappear if you have actually fixed it.

![image](https://user-images.githubusercontent.com/5531467/115555082-6c9ae880-a2af-11eb-9660-378d337ae0e4.png)

**Comment by brunomikoski** [comment]
This system changed on https://github.com/brunomikoski/ScriptableObjectCollection/tree/v1.5.4, it should not be an issue anymore since the fix is automatically applied if its now allowed (Collection script and target folder are in different assemblies)
