### ISSUE TITLE
Error while creating new collection

### ISSUE THREAD

**Issue by landosilva** [brunomikoski/ScriptableObjectCollection#93]
Just added the package into my project and tried to create a new collection. After that, the collection was not automatically created and I had this exepction:

![image](https://user-images.githubusercontent.com/9856112/144268048-3ad9d630-90b2-46f1-9332-0088d58eb2a1.png)

**Comment by brunomikoski** [comment]
Could not reproduce, what version of unity you got this?

**Comment by landosilva** [comment]
Honestly I don't remember what I was doing and how to reproduce, the only clue left is the line where the issue happened. CreateCollectionWizard:707
