### ISSUE TITLE
Collection Inspector is not updating properly

### ISSUE THREAD

**Issue by landosilva** [brunomikoski/ScriptableObjectCollection#95]
I have a Collection called "Types", and each type has a list of strengths, weaknesses and immunites of the same type as the collection item.
![image](https://user-images.githubusercontent.com/9856112/149042301-d9ac4b9f-fa1b-4bf9-b71b-0930ac3cde6d.png)
When I try to fill those lists, selecting the item does nothing.

**Comment by brunomikoski** [comment]
I could not reproduce this issue locally:
![image](https://user-images.githubusercontent.com/600419/151056887-f9178a0f-eb27-4301-a0fe-9b3a96670950.png)

Did you have a chance to check if this issue is Odin related maybe?

**Comment by landosilva** [comment]
Yes, seems like it is related to serializing lists and mainly dictionaries with Odin.

**Comment by brunomikoski** [comment]
¯\_(ツ)_/¯
 
 I will close the issue for now, but I will try to check the odin integration as soon as I can.
