### ISSUE TITLE
Progress Bar "Animatable"

### ISSUE THREAD

**Issue by landosilva** [brunomikoski/ScriptableObjectCollection#96]
Would be nice to be able to animate the progress bar via mechanim system, that way we can integrate tweens animations in the Timeline for example. This would be super powerful.

**Comment by brunomikoski** [comment]
I guess you mean for the https://github.com/brunomikoski/Animation-Sequencer right?!

**Comment by landosilva** [comment]
Oh yeah I was with both opened and didn't realize I was in the wrong one. My bad.
